apiVersion: observe/v1
kind: QueryCollection

metadata:
  folder: applications/queues

queries:
  queue_size:
    description: Queue size by deployment, priority, and state.
    datasource: prometheus
    inputs:
      deployment: {}
      priority: {}
      state: {}
    request:
      range: true
      interval: 1m
      query: max(app_queue_${inputs.priority}_${inputs.state}_size{deployment="${inputs.deployment}"}) by (deployment)

  queue_jobs_et:
    description: Average execution time for processed queue jobs by deployment, tenant, priority, and job.
    datasource: prometheus
    inputs:
      deployment: {}
      tenant: {}
      priority: {}
      job: {}
    request:
      range: true
      interval: 1m
      query: |
        topk(20, 
          (rate(app_queue_job_execution_time{deployment=~"${inputs.deployment}",tenant=~"${inputs.tenant}", priority=~"${inputs.priority}", exported_job=~"${inputs.job}"}[2m])
          / ignoring(type)
          rate(app_queue_job_count{deployment=~"${inputs.deployment}",tenant=~"${inputs.tenant}",priority=~"${inputs.priority}",type="processed", exported_job=~"${inputs.job}"}[2m])) 
          != +Inf
        )
  queue_jobs_preasure:
    description: Job preassure for processed jobs
    datasource: prometheus
    inputs:
      deployment: {}
      tenant: {}
      priority: {}
    request:
      range: true
      interval: 1m
      query: |
        topk(10,
          rate(app_queue_job_execution_time{deployment=~"${inputs.deployment}",tenant=~"${inputs.tenant}",priority=~"${inputs.priority}"}[2m])
          / ignoring(type) rate(app_queue_job_count{deployment=~"${inputs.deployment}",tenant=~"${inputs.tenant}",priority=~"${inputs.priority}",type="processed"}[2m])
          * ignoring(type) group_left rate(app_queue_job_count{deployment=~"${inputs.deployment}",tenant=~"${inputs.tenant}",priority=~"${inputs.priority}",type="processed"}[2m])
        )
