apiVersion: observe/v1
kind: DatasetCollection

metadata:
  folder: applications/queues

datasets:
  # Pending Jobs
  queue_low_pending:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: pending
        priority: low

  queue_default_pending:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: pending
        priority: default

  queue_high_pending:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: pending
        priority: high

  queue_bulk_pending:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: pending
        priority: bulk

  # Running Jobs
  queue_low_running:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: running
        priority: low

  queue_default_running:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: running
        priority: default

  queue_high_running:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: running
        priority: high

  queue_bulk_running:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: running
        priority: bulk

  # Delayed Jobs
  queue_low_delayed:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: delayed
        priority: low

  queue_default_delayed:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: delayed
        priority: default

  queue_high_delayed:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: delayed
        priority: high

  queue_bulk_delayed:
    inputs:
      deployment: {}
    source: query
    query:
      name: queue_size
      inputs:
        deployment: ${inputs.deployment}
        state: delayed
        priority: bulk

  queue_default_jobs_et:
    no_value: 0
    fill_missing: 0
    inputs:
      deployment: {}
      tenant: {}
      job: {}
    source: query
    query:
      name: queue_jobs_et
      inputs:
        deployment: ${inputs.deployment}
        tenant: ${inputs.tenant}
        job: ${inputs.job}
        priority: default

  queue_high_jobs_et:
    no_value: 0
    fill_missing: 0
    inputs:
      deployment: {}
      tenant: {}
      job: {}
    source: query
    query:
      name: queue_jobs_et
      inputs:
        deployment: ${inputs.deployment}
        tenant: ${inputs.tenant}
        job: ${inputs.job}
        priority: high

  queue_jobs_preasure:
    no_value: 0
    fill_missing: 0
    inputs:
      deployment: {}
      tenant: {}
      priority: {}
    source: query
    query:
      name: queue_jobs_preasure
      inputs:
        deployment: ${inputs.deployment}
        tenant: ${inputs.tenant}
        priority: ${inputs.priority}
