apiVersion: observe/v1
kind: Datasources

metadata:
  folder: real

datasources:
  eu-charge:
    type: prometheus
    mode: real
    url: https://prometheus.eu.infra.charge.ampeco.tech
    basic_auth:
      username: admin
      password: master@ampeco.tech

  uk-charge:
    type: prometheus
    mode: real
    url: https://prometheus.uk.infra.charge.ampeco.tech
    basic_auth:
      username: admin
      password: master@ampeco.tech
  
  us-charge:
    type: prometheus
    mode: real
    url: https://prometheus.us.infra.charge.ampeco.tech
    basic_auth:
      username: admin
      password: master@ampeco.tech

  sg-charge:
    type: prometheus
    mode: real
    url: https://prometheus.sg.infra.charge.ampeco.tech
    basic_auth:
      username: admin
      password: master@ampeco.tech

  au-charge:
    type: prometheus
    mode: real
    url: https://prometheus.au.infra.charge.ampeco.tech
    basic_auth:
      username: admin
      password: master@ampeco.tech


